POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test",
    "admin": true
}


### GET User by ID
GET http://localhost:3000/auth/1


### Find All users with a given email
GET http://localhost:3000/auth?email=rinzler.abhishek@gmail.com

### Update a user with ID
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "aaa"
}


### Delete a user with ID
DELETE http://localhost:3000/auth/2
